In [ ]:
#Ejecutar este bloque primero y luego el bloque de descomposicionQR() y metodoQR()
import numpy as np

In [3]:
#Para ejecutar la función se debe pasar la matriz A. 
#Retorna dos matrices, Q y R, con los vectores ortonormales de A y los coeficientes de proyección respectivamente
def descomposicionQR(A):
    
    n = A.shape[0]
    
    #Se inicializan Q y R con ceros.
    Q = np.zeros( (n,n), dtype=float ) #Q recibira los vectores ortonormales de A
    R = np.zeros( (n,n), dtype=float ) #R recibira los coeficientes de proyeccion 

    for i in range(n):

        v = A[:, i]

        #Se ortogonalizan los vectores de A
        for j in range(i):
            
           
            R[j,i] = np.dot(Q[:,j],v) #Se guardan por encima de la diagonal los coeficientes de proyeccion 
            v = v - R[j, i]*Q[:,j] #Se calcula la proyección 

        R[i,i] = np.linalg.norm(v) #Se guardan en la diagonal las normas de los vectores ortogonales de A
        Q[:,i] = v / R[i,i]  #Se guarda en Q los vectores ortonormales de A

    return Q, R

In [4]:
#Para ejecutar la función se debe pasar la matriz A. 
#Retorna un vector con los valores propios de A
#Hay un número maximo de iteraciones y de tolerancia por defecto, pero pueden ser modificados al llamar la función
def metodoQR(A, tol=1e-8, max_iter = 10000):
    n = A.shape[0]

    A_k = A.copy()

    for _ in range(max_iter):
        Q, R = descomposicionQR(A_k) #Se factoriza A como QR

        A_k = np.dot(R,Q) #Se reescribe A como RQ
        if np.sum(np.abs(np.tril(A_k, k=-1))) < tol:
            return np.diagonal(A_k) #Si los elementos por debajo de la diagonal son lo suficientemente pequeños que retorne la diagonal
        
    return np.diagonal(A_k)

In [7]:
#Caso 1
A = np.array( [ [2,1], [3,4]  ])
eigenvalues = metodoQR(A)
print(eigenvalues)

[5. 1.]


In [8]:
#Caso 2
A = np.array( [ [3,2], [3,4]  ])
eigenvalues = metodoQR(A)
print(eigenvalues)

[6. 1.]


In [9]:
#Caso 3
A = np.array( [ [2,3], [1,4]  ])
eigenvalues = metodoQR(A)
print(eigenvalues)

[5. 1.]


In [10]:
#Caso 4
A = np.array( [ [1,1,2], [2,1,1], [1,1,3]  ])
eigenvalues = metodoQR(A)
print(eigenvalues)

[ 4.50701864  0.77812384 -0.28514249]


In [ ]:
#Caso 5
A = np.array( [ [1,1,2], [2,1,3], [1,1,1]  ])
eigenvalues = metodoQR(A)
print(eigenvalues)

[ 4.04891734 -0.69202147 -0.35689586]


In [13]:
#Caso 6
A = np.array( [ [2,1,2], [1,1,3], [1,1,1]  ])
eigenvalues = metodoQR(A)
print(eigenvalues)

[ 4.12488542 -0.76155719  0.63667177]


In [12]:
#Caso 7
A = np.array( [ [1,1,1,2], [2,1,1,1], [3,2,1,2], [2,1,1,4]  ])
eigenvalues = metodoQR(A)
print(eigenvalues)

[ 6.63453446  1.50856334 -0.73564154 -0.40745627]


In [14]:
#Caso 8
A = np.array( [ [1,2,1,2], [2,1,1,1], [3,2,1,2], [2,1,1,4]  ])
eigenvalues = metodoQR(A)
print(eigenvalues)

[ 6.82726225  1.72811591 -1.08793492 -0.46744323]


**Comentarios**.
El método converge con bastante facilidad, pero su implementación es un poco más extensa que el método de la potencia dado el uso de Gran-Schmidt para factorizar la matriz, sin embargo el método arroja todos los valores propios, haciendolo extremadamente util, a pesar de no encontrar ninguno de los vectores propios asociados, forzando a tener que implementar un método extra para hallarlos.